INDUSTRIES = [
    (0, "Accounting"),
    (1, "Airlines/Aviation"),
    (2, "Alternative Dispute Resolution"),
    (3, "Alternative Medicine"),
    (4, "Animation"),
    (5, "Apparel & Fashion"),
    (6, "Architecture & Planning"),
    (7, "Arts and Crafts"),
    (8, "Automotive"),
    (9, "Aviation & Aerospace"),
    (10, "Banking"),
    (11, "Biotechnology"),
    (12, "Broadcast Media"),
    (13, "Building Materials"),
    (14, "Business Supplies and Equipment"),
    (15, "Capital Markets"),
    (16, "Chemicals"),
    (17, "Civic & Social Organization"),
    (18, "Civil Engineering"),
    (19, "Commercial Real Estate"),
    (20, "Computer & Network Security"),
    (21, "Computer Games"),
    (22, "Computer Hardware"),
    (23, "Computer Networking"),
    (24, "Computer Software"),
    (25, "Construction"),
    (26, "Consumer Electronics"),
    (27, "Consumer Goods"),
    (28, "Consumer Services"),
    (29, "Cosmetics"),
    (30, "Dairy"),
    (31, "Defense & Space"),
    (32, "Design"),
    (33, "Education Management"),
    (34, "E-Learning"),
    (35, "Electrical/Electronic Manufacturing"),
    (36, "Entertainment"),
    (37, "Environmental Services"),
    (38, "Events Services"),
    (39, "Executive Office"),
    (40, "Facilities Services"),
    (41, "Farming"),
    (42, "Financial Services"),
    (43, "Fine Art"),
    (44, "Fishery"),
    (45, "Food & Beverages"),
    (46, "Food Production"),
    (47, "Fund-Raising"),
    (48, "Furniture"),
    (49, "Gambling & Casinos"),
    (50, "Glass, Ceramics & Concrete"),
    (51, "Government Administration"),
    (52, "Government Relations"),
    (53, "Graphic Design"),
    (54, "Health, Wellness and Fitness"),
    (55, "Higher Education"),
    (56, "Hospital & Health Care"),
    (57, "Hospitality"),
    (58, "Human Resources"),
    (59, "Import and Export"),
    (60, "Individual & Family Services"),
    (61, "Industrial Automation"),
    (62, "Information Services"),
    (63, "Information Technology and Services"),
    (64, "Insurance"),
    (65, "International Affairs"),
    (66, "International Trade and Development"),
    (67, "Internet"),
    (68, "Investment Banking"),
    (69, "Investment Management"),
    (70, "Judiciary"),
    (71, "Law Enforcement"),
    (72, "Law Practice"),
    (73, "Legal Services"),
    (74, "Legislative Office"),
    (75, "Leisure, Travel & Tourism"),
    (76, "Libraries"),
    (77, "Logistics and Supply Chain"),
    (78, "Luxury Goods & Jewelry"),
    (79, "Machinery"),
    (80, "Management Consulting"),
    (81, "Maritime"),
    (82, "Market Research"),
    (83, "Marketing and Advertising"),
    (84, "Mechanical or Industrial Engineering"),
    (85, "Media Production"),
    (86, "Medical Devices"),
    (87, "Medical Practice"),
    (88, "Mental Health Care"),
    (89, "Military"),
    (90, "Mining & Metals"),
    (91, "Motion Pictures and Film"),
    (92, "Museums and Institutions"),
    (93, "Music"),
    (94, "Nanotechnology"),
    (95, "Newspapers"),
    (96, "Non-Profit Organization Management"),
    (97, "Oil & Energy"),
    (98, "Online Media"),
    (99, "Outsourcing/Offshoring"),
    (100, "Package/Freight Delivery"),
    (101, "Packaging and Containers"),
    (102, "Paper & Forest Products"),
    (103, "Performing Arts"),
    (104, "Pharmaceuticals"),
    (105, "Philanthropy"),
    (106, "Photography"),
    (107, "Plastics"),
    (108, "Political Organization"),
    (109, "Primary/Secondary Education"),
    (110, "Printing"),
    (111, "Professional Training & Coaching"),
    (112, "Program Development"),
    (113, "Public Policy"),
    (114, "Public Relations and Communications"),
    (115, "Public Safety"),
    (116, "Publishing"),
    (117, "Railroad Manufacture"),
    (118, "Ranching"),
    (119, "Real Estate"),
    (120, "Recreational Facilities and Services"),
    (121, "Religious Institutions"),
    (122, "Renewables & Environment"),
    (123, "Research"),
    (124, "Restaurants"),
    (125, "Retail"),
    (126, "Security and Investigations"),
    (127, "Semiconductors"),
    (128, "Shipbuilding"),
    (129, "Sporting Goods"),
    (130, "Sports"),
    (131, "Staffing and Recruiting"),
    (132, "Supermarkets"),
    (133, "Telecommunications"),
    (134, "Textiles"),
    (135, "Think Tanks"),
    (136, "Tobacco"),
    (137, "Translation and Localization"),
    (138, "Transportation/Trucking/Railroad"),
    (139, "Utilities"),
    (140, "Venture Capital & Private Equity"),
    (141, "Veterinary"),
    (142, "Warehousing"),
    (143, "Wholesale"),
    (144, "Wine and Spirits"),
    (145, "Wireless"),
    (146, "Writing and Editing"),
]

COMPANY_SIZES = [
    (0, "Self-employed"),
    (1, "1-10 employees"),
    (2, "11-50 employees"),
    (3, "51-200 employees"),
    (4, "201-500 employees"),
    (5, "501-1000 employees"),
    (6, "1001-5000 employees"),
    (7, "5001-10,000 employees"),
    (8, "10,001+ employees"),
]

SENIORITY_LEVELS = [
    (0, "Internship / Trainee"),
    (1, "Entry-level"),
    (2, "Senior"),
    (3, "Manager"),
    (4, "Director"),
    (5, "Vice President"),
    (6, "Chief X Officer (CXO)"),
    (7, "Partner"),
    (8, "Owner"),
]

JOB_FUNCTIONS = [
    (0, "Accounting"),
    (1, "Administrative"),
    (2, "Arts and Design"),
    (3, "Business Development"),
    (4, "Community & Social Services"),
    (5, "Consulting"),
    (6, "Education"),
    (7, "Engineering"),
    (8, "Entrepreneurship"),
    (9, "Finance"),
    (10, "Healthcare Services"),
    (11, "Human Resources"),
    (12, "Information Technology"),
    (13, "Legal"),
    (14, "Marketing"),
    (15, "Media & Communications"),
    (16, "Military & Protective Services"),
    (17, "Operations"),
    (18, "Product Management"),
    (19, "Program & Product Management"),
    (20, "Purchasing"),
    (21, "Quality Assurance"),
    (22, "Real Estate"),
    (23, "Research"),
    (24, "Sales"),
    (25, "Support"),
]

STATS_COMPANY_SIZES = [
    (0, "Self-employed"),
    (1, "1-10"),
    (2, "11-50"),
    (3, "51-200"),
    (4, "201-500"),
    (5, "501-1000"),
    (6, "1001-5000"),
    (7, "5001-10,000"),
    (8, "10,000+"),
]

STATS_SENIORITY = [
    (0, "Training"),
    (1, "Entry"),
    (2, "Senior"),
    (3, "Manager"),
    (4, "Director"),
    (5, "VP"),
    (6, "CXO"),
    (7, "Partner"),
    (8, "Owner"),
]

STATS_INDUSTRIES = [
    (0, "Accounting"),
    (1, "Airlines/Aviation"),
    (2, "Alternative Dispute Resolution"),
    (3, "Alternative Medicine"),
    (4, "Animation"),
    (5, "Apparel & Fashion"),
    (6, "Architecture & Planning"),
    (7, "Arts and Crafts"),
    (8, "Automotive"),
    (9, "Aviation & Aerospace"),
    (10, "Banking"),
    (11, "Biotechnology"),
    (12, "Broadcast Media"),
    (13, "Building Materials"),
    (14, "Business Supplies and Equipment"),
    (15, "Capital Markets"),
    (16, "Chemicals"),
    (17, "Civic & Social Organization"),
    (18, "Civil Engineering"),
    (19, "Commercial Real Estate"),
    (20, "Computer & Network Security"),
    (21, "Computer Games"),
    (22, "Computer Hardware"),
    (23, "Computer Networking"),
    (24, "Computer Software"),
    (25, "Construction"),
    (26, "Consumer Electronics"),
    (27, "Consumer Goods"),
    (28, "Consumer Services"),
    (29, "Cosmetics"),
    (30, "Dairy"),
    (31, "Defense & Space"),
    (32, "Design"),
    (33, "Education Management"),
    (34, "E-Learning"),
    (35, "Electrical/Electronic Manufacturing"),
    (36, "Entertainment"),
    (37, "Environmental Services"),
    (38, "Events Services"),
    (39, "Executive Office"),
    (40, "Facilities Services"),
    (41, "Farming"),
    (42, "Financial Services"),
    (43, "Fine Art"),
    (44, "Fishery"),
    (45, "Food & Beverages"),
    (46, "Food Production"),
    (47, "Fund-Raising"),
    (48, "Furniture"),
    (49, "Gambling & Casinos"),
    (50, "Glass, Ceramics & Concrete"),
    (51, "Government Administration"),
    (52, "Government Relations"),
    (53, "Graphic Design"),
    (54, "Health, Wellness and Fitness"),
    (55, "Higher Education"),
    (56, "Hospital & Health Care"),
    (57, "Hospitality"),
    (58, "Human Resources"),
    (59, "Import and Export"),
    (60, "Individual & Family Services"),
    (61, "Industrial Automation"),
    (62, "Information Services"),
    (63, "Information Technology and Services"),
    (64, "Insurance"),
    (65, "International Affairs"),
    (66, "International Trade and Development"),
    (67, "Internet"),
    (68, "Investment Banking"),
    (69, "Investment Management"),
    (70, "Judiciary"),
    (71, "Law Enforcement"),
    (72, "Law Practice"),
    (73, "Legal Services"),
    (74, "Legislative Office"),
    (75, "Leisure, Travel & Tourism"),
    (76, "Libraries"),
    (77, "Logistics and Supply Chain"),
    (78, "Luxury Goods & Jewelry"),
    (79, "Machinery"),
    (80, "Management Consulting"),
    (81, "Maritime"),
    (82, "Market Research"),
    (83, "Marketing and Advertising"),
    (84, "Mechanical or Industrial Engineering"),
    (85, "Media Production"),
    (86, "Medical Devices"),
    (87, "Medical Practice"),
    (88, "Mental Health Care"),
    (89, "Military"),
    (90, "Mining & Metals"),
    (91, "Motion Pictures and Film"),
    (92, "Museums and Institutions"),
    (93, "Music"),
    (94, "Nanotechnology"),
    (95, "Newspapers"),
    (96, "Nonprofit Organization Management"),
    (97, "Oil & Energy"),
    (98, "Online Media"),
    (99, "Outsourcing/Offshoring"),
    (100, "Package/Freight Delivery"),
    (101, "Packaging and Containers"),
    (102, "Paper & Forest Products"),
    (103, "Performing Arts"),
    (104, "Pharmaceuticals"),
    (105, "Philanthropy"),
    (106, "Photography"),
    (107, "Plastics"),
    (108, "Political Organization"),
    (109, "Primary/Secondary Education"),
    (110, "Printing"),
    (111, "Professional Training & Coaching"),
    (112, "Program Development"),
    (113, "Public Policy"),
    (114, "Public Relations and Communications"),
    (115, "Public Safety"),
    (116, "Publishing"),
    (117, "Railroad Manufacture"),
    (118, "Ranching"),
    (119, "Real Estate"),
    (120, "Recreational Facilities and Services"),
    (121, "Religious Institutions"),
    (122, "Renewables & Environment"),
    (123, "Research"),
    (124, "Restaurants"),
    (125, "Retail"),
    (126, "Security and Investigations"),
    (127, "Semiconductors"),
    (128, "Shipbuilding"),
    (129, "Sporting Goods"),
    (130, "Sports"),
    (131, "Staffing and Recruiting"),
    (132, "Supermarkets"),
    (133, "Telecommunications"),
    (134, "Textiles"),
    (135, "Think Tanks"),
    (136, "Tobacco"),
    (137, "Translation and Localization"),
    (138, "Transportation/Trucking/Railroad"),
    (139, "Utilities"),
    (140, "Venture Capital & Private Equity"),
    (141, "Veterinary"),
    (142, "Warehousing"),
    (143, "Wholesale"),
    (144, "Wine and Spirits"),
    (145, "Wireless"),
    (146, "Writing and Editing"),
]

STATS_JOB_FUNCTIONS = [
    (0, "Accounting"),
    (1, "Administrative"),
    (2, "Arts and Design"),
    (3, "Business Development"),
    (4, "Community and Social Services"),
    (5, "Consulting"),
    (6, "Education"),
    (7, "Engineering"),
    (8, "Entrepreneurship"),
    (9, "Finance"),
    (10, "Healthcare Services"),
    (11, "Human Resources"),
    (12, "Information Technology"),
    (13, "Legal"),
    (14, "Marketing"),
    (15, "Media and Communication"),
    (16, "Military and Protective Services"),
    (17, "Operations"),
    (18, "Product Management"),
    (19, "Program and Project Management"),
    (20, "Purchasing"),
    (21, "Quality Assurance"),
    (22, "Real Estate"),
    (23, "Research"),
    (24, "Sales"),
    (25, "Support"),
]